# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBI-Wrapper
version:      0.04
version_from: lib/DBI/Wrapper.pm
installdirs:  site
requires:
    DBI:                           1.34

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
