# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBIx-Wrapper-VerySimple
version:      0.051
version_from: lib/DBIx/Wrapper/VerySimple.pm
installdirs:  site
requires:
    DBI:                           1.34

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
